# Generated by Django 5.1.3 on 2025-01-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0003_alter_shift_shift_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift_priority',
        ),
    ]
