# Generated by Django 5.1.3 on 2025-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0004_remove_shift_shift_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
