# Generated by Django 5.1.3 on 2025-01-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0005_shift_shift_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
