# Generated by Django 5.1.3 on 2025-01-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0006_alter_shift_shift_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
