# Generated by Django 5.1.3 on 2025-02-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0007_alter_shift_shift_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift_day',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_priority',
        ),
    ]
