# Generated by Django 5.1.3 on 2025-01-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=50)),
                ('no_of_hours_worked', models.IntegerField()),
                ('designation', models.CharField(max_length=50)),
                ('e_email', models.EmailField(max_length=100)),
                ('e_priority', models.IntegerField()),
            ],
        ),
    ]
