# Generated by Django 5.1.3 on 2025-01-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='e_email',
            new_name='e_gmail',
        ),
    ]
