# Generated by Django 5.1.3 on 2025-01-29 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrmanager',
            name='name',
        ),
        migrations.AddField(
            model_name='hrmanager',
            name='ManagerID',
            field=models.CharField(default='0000', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Manager ID must be exactly 4 digits')]),
        ),
    ]
