# Generated by Django 5.1.3 on 2025-01-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_hrmanager_name_hrmanager_managerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmanager',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
