# Generated by Django 5.0.10 on 2025-02-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_hrmanager_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmanager',
            name='email',
            field=models.EmailField(default='hrmanager@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='hrmanager',
            name='username',
            field=models.CharField(default='HRManager', max_length=150),
        ),
    ]
