import os
import django
import sys

sys.path.append('C:\\Users\\ASUS\\Desktop\\SAS')

# Set the DJANGO_SETTINGS_MODULE environment variable to your settings module
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')

# Initialize Django
django.setup()

from configure.models import Employee
# Insert Employee Data
employee_data = [(1, 'John Doe', 0, 'Cashier', 'john.doe@yahoo.com', 8),
(2, 'Jane Smith', 0, 'Cashier', 'jane.smith@yahoo.com', 8),
(3, 'Mark Lee', 0, 'Cashier', 'mark.lee@yahoo.com', 8),
(4, 'Anna White', 0, 'Cashier', 'anna.white@yahoo.com', 8),
(5, 'Chris Green', 0, 'Cashier', 'chris.green@yahoo.com', 8),
(6, 'Sarah Black', 0, 'Cashier', 'sarah.black@yahoo.com', 8),
(7, 'Tom Brown', 0, 'Cashier', 'tom.brown@yahoo.com', 8),
(8, 'Emily Clark', 0, 'Cashier', 'emily.clark@yahoo.com', 8),
(9, 'Daniel King', 0, 'Cashier', 'daniel.king@yahoo.com', 8),
(10, 'Laura Scott', 0, 'Cashier', 'laura.scott@yahoo.com', 8),
(11, 'Jack Hill', 0, 'Cashier', 'jack.hill@yahoo.com', 8),
(12, 'Olivia Adams', 0, 'Cashier', 'olivia.adams@yahoo.com', 8),
(13, 'Liam Turner', 0, 'Cashier', 'liam.turner@yahoo.com', 8),
(14, 'Sophia Evans', 0, 'Cashier', 'sophia.evans@yahoo.com', 8),
(15, 'Mason Hall', 0, 'Cashier', 'mason.hall@yahoo.com', 8),
(16, 'Ella Ward', 0, 'Cashier', 'ella.ward@yahoo.com', 8),
(17, 'Jacob Carter', 0, 'Cashier', 'jacob.carter@yahoo.com', 8),
(18, 'Ava Mitchell', 0, 'Cashier', 'ava.mitchell@yahoo.com', 8),
(19, 'Michael Brooks', 0, 'Cashier', 'michael.brooks@yahoo.com', 8),
(20, 'Grace Lewis', 0, 'Cashier', 'grace.lewis@yahoo.com', 8),
(21, 'Alice Johnson', 0, 'Supervisor', 'alice.johnson@gmail.com', 8),
(22, 'Bob Smith', 0, 'Supervisor', 'bob.smith@gmail.com', 8),
(23, 'Charlie Davis', 0, 'Supervisor', 'charlie.davis@gmail.com', 8),
(24, 'Diana Clark', 0, 'Supervisor', 'diana.clark@gmail.com', 8),
(25, 'Ethan Brown', 0, 'Supervisor', 'ethan.brown@gmail.com', 8),
(26, 'Fiona Adams', 0, 'Supervisor', 'fiona.adams@gmail.com', 8),
(27, 'George Miller', 0, 'Supervisor', 'george.miller@gmail.com', 8),
(28, 'Hannah White', 0, 'Supervisor', 'hannah.white@gmail.com', 8),
(29, 'Isaac Wilson', 0, 'Supervisor', 'isaac.wilson@gmail.com', 8),
(30, 'Julia Thomas', 0, 'Supervisor', 'julia.thomas@gmail.com', 8),
(31, 'Kevin Moore', 0, 'Supervisor', 'kevin.moore@gmail.com', 8),
(32, 'Liam Taylor', 0, 'Supervisor', 'liam.taylor@gmail.com', 8),
(33, 'Mia Scott', 0, 'Supervisor', 'mia.scott@gmail.com', 8),
(34, 'Nathan Harris', 0, 'Supervisor', 'nathan.harris@gmail.com', 8),
(35, 'Olivia Martinez', 0, 'Supervisor', 'olivia.martinez@gmail.com', 8),
(36, 'Peter Robinson', 0, 'Supervisor', 'peter.robinson@gmail.com', 8),
(37, 'Quinn Lewis', 0, 'Supervisor', 'quinn.lewis@gmail.com', 8),
(38, 'Rachel Walker', 0, 'Supervisor', 'rachel.walker@gmail.com', 8),
(39, 'Samuel Allen', 0, 'Supervisor', 'samuel.allen@gmail.com', 8),
(40, 'Tina Young', 0, 'Supervisor', 'tina.young@gmail.com', 8),
(41, 'John Doe', 0, 'Inventory Manager', 'john.doe@hotmail.com', 6),
(42, 'Jane Smith', 0, 'Inventory Manager', 'jane.smith@hotmail.com', 6),
(43, 'Mike Johnson', 0, 'Inventory Manager', 'mike.johnson@hotmail.com', 6),
(44, 'Emily Davis', 0, 'Inventory Manager', 'emily.davis@hotmail.com', 6),
(45, 'Chris Wilson', 0, 'Inventory Manager', 'chris.wilson@hotmail.com', 6),
(46, 'Sarah Brown', 0, 'Inventory Manager', 'sarah.brown@hotmail.com', 6),
(47, 'David Martinez', 0, 'Inventory Manager', 'david.martinez@hotmail.com', 6),
(48, 'Anna Taylor', 0, 'Inventory Manager', 'anna.taylor@hotmail.com', 6),
(49, 'James Anderson', 0, 'Inventory Manager', 'james.anderson@hotmail.com', 6),
(50, 'Laura Thomas', 0, 'Inventory Manager', 'laura.thomas@hotmail.com', 6),
(51, 'Robert White', 0, 'Inventory Manager', 'robert.white@hotmail.com', 6),
(52, 'Patricia Harris', 0, 'Inventory Manager', 'patricia.harris@hotmail.com', 6),
(53, 'Linda Clark', 0, 'Inventory Manager', 'linda.clark@hotmail.com', 6),
(54, 'Steven Lewis', 0, 'Inventory Manager', 'steven.lewis@hotmail.com', 6),
(55, 'Jessica Walker', 0, 'Inventory Manager', 'jessica.walker@hotmail.com', 6),
(56, 'Matthew Hall', 0, 'Inventory Manager', 'matthew.hall@hotmail.com', 6),
(57, 'Olivia Allen', 0, 'Inventory Manager', 'olivia.allen@hotmail.com', 6),
(58, 'Daniel Young', 0, 'Inventory Manager', 'daniel.young@hotmail.com', 6),
(59, 'Sophia King', 0, 'Inventory Manager', 'sophia.king@hotmail.com', 6),
(60, 'Brian Wright', 0, 'Inventory Manager', 'brian.wright@hotmail.com', 6),
(61, 'Karen Scott', 0, 'Inventory Manager', 'karen.scott@hotmail.com', 6),
(62, 'Jason Green', 0, 'Inventory Manager', 'jason.green@hotmail.com', 6),
(63, 'Nancy Adams', 0, 'Inventory Manager', 'nancy.adams@hotmail.com', 6),
(64, 'Paul Baker', 0, 'Inventory Manager', 'paul.baker@hotmail.com', 6),
(65, 'Rebecca Gonzalez', 0, 'Inventory Manager', 'rebecca.gonzalez@hotmail.com', 6),
(66, 'Alice Johnson', 0, 'Customer Help', 'alice.johnson@gmail.com', 8),
(67, 'Bob Smith', 0, 'Customer Help', 'bob.smith@gmail.com', 8),
(68, 'Charlie Davis', 0, 'Customer Help', 'charlie.davis@gmail.com', 8),
(69, 'David Lee', 0, 'Customer Help', 'david.lee@gmail.com', 8),
(70, 'Eva Brown', 0, 'Customer Help', 'eva.brown@gmail.com', 8),
(71, 'Fiona Williams', 0, 'Customer Help', 'fiona.williams@gmail.com', 8),
(72, 'George Taylor', 0, 'Customer Help', 'george.taylor@gmail.com', 8),
(73, 'Hannah Martinez', 0, 'Customer Help', 'hannah.martinez@gmail.com', 8),
(74, 'Ivy Moore', 0, 'Customer Help', 'ivy.moore@gmail.com', 8),
(75, 'Jack Anderson', 0, 'Customer Help', 'jack.anderson@gmail.com', 8),
(76, 'Karen Thomas', 0, 'Customer Help', 'karen.thomas@gmail.com', 8),
(77, 'Leo Jackson', 0, 'Customer Help', 'leo.jackson@gmail.com', 8),
(78, 'Mia White', 0, 'Customer Help', 'mia.white@gmail.com', 8),
(79, 'Nathan Harris', 0, 'Customer Help', 'nathan.harris@gmail.com', 8),
(80, 'Olivia Clark', 0, 'Customer Help', 'olivia.clark@gmail.com', 8),
(81, 'Paul Lewis', 0, 'Customer Help', 'paul.lewis@gmail.com', 8),
(82, 'Quinn Walker', 0, 'Customer Help', 'quinn.walker@gmail.com', 8),
(83, 'Rachel Hall', 0, 'Customer Help', 'rachel.hall@gmail.com', 8),
(84, 'Samuel Allen', 0, 'Customer Help', 'samuel.allen@gmail.com', 8),
(85, 'Tina Young', 0, 'Customer Help', 'tina.young@gmail.com', 8),
(86, 'Ursula King', 0, 'Customer Help', 'ursula.king@gmail.com', 8),
(87, 'Victor Scott', 0, 'Customer Help', 'victor.scott@gmail.com', 8),
(88, 'Wendy Green', 0, 'Customer Help', 'wendy.green@gmail.com', 8),
(89, 'Xander Adams', 0, 'Customer Help', 'xander.adams@gmail.com', 8),
(90, 'Yara Nelson', 0, 'Customer Help', 'yara.nelson@gmail.com', 8),
(91, 'John Doe', 0, 'Cleaning Staff', 'john.doe@yahoo.com', 4),
(92, 'Jane Smith', 0, 'Cleaning Staff', 'jane.smith@yahoo.com', 4),
(93, 'Chris Brown', 0, 'Cleaning Staff', 'chris.brown@yahoo.com', 4),
(94, 'Sarah Johnson', 0, 'Cleaning Staff', 'sarah.johnson@yahoo.com', 4),
(95, 'Michael White', 0, 'Cleaning Staff', 'michael.white@yahoo.com', 4),
(96, 'Emily Davis', 0, 'Cleaning Staff', 'emily.davis@yahoo.com', 4),
(97, 'David Clark', 0, 'Cleaning Staff', 'david.clark@yahoo.com', 4),
(98, 'Olivia Lewis', 0, 'Cleaning Staff', 'olivia.lewis@yahoo.com', 4),
(99, 'James Harris', 0, 'Cleaning Staff', 'james.harris@yahoo.com', 4),
(100, 'Sophia Walker', 0, 'Cleaning Staff', 'sophia.walker@yahoo.com', 4),
(101, 'Benjamin Hall', 0, 'Cleaning Staff', 'benjamin.hall@yahoo.com', 4),
(102, 'Mia Allen', 0, 'Cleaning Staff', 'mia.allen@yahoo.com', 4),
(103, 'Ethan Young', 0, 'Cleaning Staff', 'ethan.young@yahoo.com', 4),
(104, 'Isabella King', 0, 'Cleaning Staff', 'isabella.king@yahoo.com', 4),
(105, 'Matthew Scott', 0, 'Cleaning Staff', 'matthew.scott@yahoo.com', 4),
(106, 'John Smith', 0, 'Manager', 'john.smith@example.com', 9),
(107, 'Alice Brown', 0, 'Manager', 'alice.brown@example.com', 9),
(108, 'Bob Johnson', 0, 'Manager', 'bob.johnson@example.com', 9),
(109, 'Carol White', 0, 'Manager', 'carol.white@example.com', 9),
(110, 'David Green', 0, 'Manager', 'david.green@example.com', 9),
(111, 'Eva Adams', 0, 'Manager', 'eva.adams@example.com', 9),
(112, 'Frank Lee', 0, 'Manager', 'frank.lee@example.com', 9),
(113, 'Grace Miller', 0, 'Manager', 'grace.miller@example.com', 9),
(114, 'Harry Clark', 0, 'Manager', 'harry.clark@example.com', 9),
(115, 'Ivy Scott', 0, 'Manager', 'ivy.scott@example.com', 9),
(116, 'Jack Walker', 0, 'Manager', 'jack.walker@example.com', 9),
(117, 'Kathy Hall', 0, 'Manager', 'kathy.hall@example.com', 9),
(118, 'Liam Allen', 0, 'Manager', 'liam.allen@example.com', 9),
(119, 'Mona Perez', 0, 'Manager', 'mona.perez@example.com', 9),
(120, 'Nathan Young', 0, 'Manager', 'nathan.young@example.com', 9)
]

for e in employee_data:
    Employee.objects.create(
        e_id=e[0], e_name=e[1], no_of_hours_worked=e[2], 
        designation=e[3], e_gmail=e[4], e_priority=e[5]
    )

